

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: IssueTrackerDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=IssueTrackerDb;Username=postgres;Password=Password123!
    expose:
      - "8080"
    depends_on:
      - db
  proxy:
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
        - BACKEND_URL=http://api:8080
    depends_on:
      - api





volumes:
  postgres_data:
