// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: activity.proto

package activitypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivityLogger_LogActivity_FullMethodName = "/activity.ActivityLogger/LogActivity"
)

// ActivityLoggerClient is the client API for ActivityLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityLoggerClient interface {
	LogActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityResponse, error)
}

type activityLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityLoggerClient(cc grpc.ClientConnInterface) ActivityLoggerClient {
	return &activityLoggerClient{cc}
}

func (c *activityLoggerClient) LogActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityResponse)
	err := c.cc.Invoke(ctx, ActivityLogger_LogActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityLoggerServer is the server API for ActivityLogger service.
// All implementations must embed UnimplementedActivityLoggerServer
// for forward compatibility.
type ActivityLoggerServer interface {
	LogActivity(context.Context, *ActivityRequest) (*ActivityResponse, error)
	mustEmbedUnimplementedActivityLoggerServer()
}

// UnimplementedActivityLoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityLoggerServer struct{}

func (UnimplementedActivityLoggerServer) LogActivity(context.Context, *ActivityRequest) (*ActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogActivity not implemented")
}
func (UnimplementedActivityLoggerServer) mustEmbedUnimplementedActivityLoggerServer() {}
func (UnimplementedActivityLoggerServer) testEmbeddedByValue()                        {}

// UnsafeActivityLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityLoggerServer will
// result in compilation errors.
type UnsafeActivityLoggerServer interface {
	mustEmbedUnimplementedActivityLoggerServer()
}

func RegisterActivityLoggerServer(s grpc.ServiceRegistrar, srv ActivityLoggerServer) {
	// If the following call panics, it indicates UnimplementedActivityLoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityLogger_ServiceDesc, srv)
}

func _ActivityLogger_LogActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLoggerServer).LogActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityLogger_LogActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLoggerServer).LogActivity(ctx, req.(*ActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityLogger_ServiceDesc is the grpc.ServiceDesc for ActivityLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.ActivityLogger",
	HandlerType: (*ActivityLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogActivity",
			Handler:    _ActivityLogger_LogActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
