name: Issue Tracker CI/CD Pipeline

"on":
  push:
    branches:
      - master
    paths:
        - 'IssueTracker/**'
        - '*.sln'
        - 'Dockerfile'
        - 'Proxy/**'
        - 'docker-compose.yml'
        - 'NotificationService/**'
  pull_request:
    branches:
      - master
    paths:
        - 'IssueTracker/**'
        - '*.sln'
        - 'Dockerfile'
        - 'Proxy/**'
        - 'docker-compose.yml'  
        - 'NotificationService/**'  
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Restore dependencies
      run: dotnet restore "IssueTracker/IssueTracker.API.csproj"
    - name: Build
      run: dotnet build "IssueTracker/IssueTracker.API.csproj" --no-restore -c Release
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: 'login to Docker Hub'
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'build and push'
      uses: docker/build-push-action@v5
      with: 
        context: ./
        file: ./Dockerfile
        push: true 
        tags: ahmedhossam09/issue-api:latest
        provenance: false
        outputs: type=registry,oci-mediatypes=false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        

  
  build-and-push-proxy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
          cache-dependency-path: Proxy/go.sum

      - name: verify code compile
        working-directory: ./Proxy
        run: |
          go mod download || true
          go build -o proxy-engine main.go
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'login to Docker Hub'
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 'build and push'
        uses: docker/build-push-action@v5
        with: 
          context: ./Proxy
          file: ./Proxy/Dockerfile
          push: true 
          tags: ahmedhossam09/issue-proxy:latest
          provenance: false
          outputs: type=registry,oci-mediatypes=false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-and-push-notifications:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
          cache-dependency-path: NotificationService/go.sum
      - name: verify code compile
        working-directory: ./NotificationService
        run: |
          go mod download || true
          go build -o notification-engine main.go
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'login to Docker Hub'
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 'build and push'
        uses: docker/build-push-action@v5
        with: 
          context: ./NotificationService
          file: ./NotificationService/Dockerfile
          push: true 
          tags: ahmedhossam09/issue-notifications:latest
          provenance: false
          outputs: type=registry,oci-mediatypes=false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
  

  